### ISSUE TITLE
Inconsistent JVM-target compatibility

### ISSUE THREAD

**Issue by yamashita-room-335** [svprdga/async_preferences#32]
I have a problem similar to this Issue(#29).

Whether it occurs or not seems to depend on the kotlin version.
The build seems to succeed if the version of Kotlin is 1.7.X and fail if the version is 1.8.X or higher.

* android/settings.gradle
```android/settings.gradle
plugins {
    ...
//    // -> Build Success
//    id "org.jetbrains.kotlin.android" version "1.7.10" apply false

    // -> Build Failed
    id "org.jetbrains.kotlin.android" version "1.8.22" apply false
}
```

* android/app/build.gradle
```android/app/build.gradle
android {
    ...
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
}
```

* android/gradle/wrapper/gradle-wrapper.properties
```android/gradle/wrapper/gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-8.9-all.zip
```

---
### Build Result
```.bat
Launching lib\main.dart on XXXXXX in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':async_preferences:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 28s
Error: Gradle task assembleDebug failed with exit code 1
```

Many people who have updated to Android Studio Ladybug have encountered the following problem, and will probably take action to increase the Gradle version, and while at it, increase the kotlin version.
https://github.com/flutter/flutter/issues/156307
https://github.com/flutter/flutter/issues/156111
Also, since google_mobile_ads: 5.2.0 requires kotlin version 1.8.X or higher, I think many people will encounter this problem given that many people use this library with respect to advertising.
Therefore, we would appreciate it if you could address this issue.

**Comment by minhdanh** [comment]
I encountered this today and this is how I fixed it: https://github.com/svprdga/async_preferences/pull/33/files

**Comment by svprdga** [comment]
You can now use version [1.0.1](https://pub.dev/packages/async_preferences/versions/1.0.1) of the plugin, which fixes this bug. Thank you for taking the time to report/fix this issue.
